name: Update ECR Repos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: |
          echo The event name is ${{ github.event_name }}
          echo The branch is ${{ github.ref }}
          echo The SHA is ${{ github.sha }}
          echo This was a ${{ github.event.action }} event
